language: ruby
rvm:
 - 2.2.3

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
