development:
   adapter: postgresql
   enconding: unicode
   database: micro_blog_dev
   pool: 5
   username: ice
   password: ice123
   host: localhost

production:
   adapter: postgresql
   enconding: unicode
   database: micro_blog
   pool: 5
