# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 237ea3749e8e3a52c76ef61c9eb426ea8208ec41e64b770f76e8db449beeee883fe5bab28aef4950525e5a8b23ed5037a55d2be5bb23dc281387d3074925cc7c

test:
  secret_key_base: ed0c83183a416a7d92905b33c1885d71e11c077abe480b952e8f12d2f93fa60ed69cf3cba090a8165527a324b5be918ad3b099b8705fc7c4c1f5ea23b1205948

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
